# Generated by Django 3.0.8 on 2020-07-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lead',
            new_name='Coupon',
        ),
    ]
